IF
	Global("C0MMinSpawn","ar1000",0)
THEN
RESPONSE #100
	SetGlobal("C0MMinSpawn","ar1000",1)
	CreateCreatureImpassable("C0MMin",[2470.285],SSW)
	RealSetGlobalTimer("C0MMinSinging","ar1000",6)
END

IF
	Global("C0MMinBegin","GLOBAL",0)
	!BeenInParty("C0MMin")
	!Allegiance("C0MMin",ENEMY)
	!Dead("C0MMin")
	RealGlobalTimerExpired("C0MMinSinging","ar1000")
	Switch("C0MMinStart","ar1000")
THEN
  RESPONSE #0
	DisplayStringHead("C0MMin",@190)
	RealSetGlobalTimer("C0MMinSinging","ar1000",10)
	SetGlobal("C0MMinStart","ar1000",1)
  RESPONSE #1
	DisplayStringHead("C0MMin",@191)
	RealSetGlobalTimer("C0MMinSinging","ar1000",5)
	SetGlobal("C0MMinStart","ar1000",2)
  RESPONSE #2
	DisplayStringHead("C0MMin",@192)
	RealSetGlobalTimer("C0MMinSinging","ar1000",10)
	SetGlobal("C0MMinStart","ar1000",3)
  RESPONSE #3
	DisplayStringHead("C0MMin",@193)
	SetGlobal("C0MMinStart","ar1000",4)
END