IF
	PartyRested()
	!Global("C0AlchemyRefreshStock","GLOBAL",1)
THEN
  RESPONSE #100
	SetGlobal("C0AlchemyRefreshStock","GLOBAL",1)
END

// Set Romance Match

IF
	!CheckStatGT(Player1,9,CHR)
	Global("C0MMinMatch","GLOBAL",0)
THEN
  RESPONSE #100
	SetGlobal("C0KarihiMatch","GLOBAL",-1)
END

IF
	CheckStatGT(Player1,9,CHR)
	Global("C0MMinMatch","GLOBAL",0)
THEN
  RESPONSE #100
	SetGlobal("C0MMinMatch","GLOBAL",1)
END
