///////////////////////////////////////////////////////////////////////////////
//////////////////////////////////// KIT //////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

ADD_KIT ~C0ARFT~
 // appended to CLASWEAP.2da
 ~C0ARFT		1           1           1           1           1           1           1           1~
 // appended column-wise to WEAPPROF.2da
//11                                T   S           F   Q             S S
//10                                W   C           L   U             W I
//9                         B L S   O   I   W       A   A             O N
//8                         A O H   H   M   A       I   R C   S       R G
//7         L S           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6         _ _       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5         S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4         W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3         O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2         R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1         D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
 ~C0ARFT	2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
 // appended to ABCLASRQ.2da
 ~C0ARFT				9      9	0	15	0	0~
 // appended to ABCLSMOD.2da
 ~C0ARFT				0	0	0	0	0	0~
 // appended to ABDCDSRQ.2da
 ~C0ARFT                		0       0       0       0       0       0~
 // appended to ABDCSCRQ.2da
 ~C0ARFT                 	0       0       0       0       0	0~
 // appended to ALIGNMNT.2da
 ~C0ARFT                  	1       1       1       1      1	1       1       1       1~
 // appended to DUALCLAS.2da
 ~C0ARFT                  	0       0       0       0       0       0~
 // path to your CLAB-style 2da file 
 ~%MOD_FOLDER%/2da/C0ARFTCL.2da~
 // PC races and classes allowed to use this kit, from KITTABLE.2da
 ~~
 // usability flags, added to the end of the KITLIST.2da entry
 ~0x00000000     9~
 // HLA table to use; see LUABBR.2da
 ~C0ARFT~
 // list of starting equipment for PCs starting in ToB. Appended column-wise to 25STWEAP.2da
 ~CHAN09 * HELM07 BAG20 RING06 RING21 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
 // Lower, mixed, and help kit names and descriptions, added to KITLIST.2da
  SAY @3
  SAY @4
  SAY @5

LAF fl#add_kit_ee
  STR_VAR
    kit_name = C0ARFT
	backstab = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
	sneakatt = ~0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	crippstr = ~0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~ 
    clswpbon = ~1 0 2~
	thiefskl = ~40 20~
END

LAF qd_multiclass
	STR_VAR
		kit_name = C0ARFT
		kit_clab = C0ARFTCL
		base_class = ~T~
		mc_dir = ~%MOD_FOLDER%/2da~
END

COPY_EXISTING ~c0aukt1.spl~ ~override~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 290 target = 2 timing = 9 parameter1 = RESOLVE_STR_REF (@6) special = 4 END

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////// SPELLS //////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

COPY_EXISTING ~c0auin1.2da~ ~override~
COPY_EXISTING ~c0auin1.spl~ ~override~
SAY NAME1 @7
SAY NAME2 @7
SAY UNIDENTIFIED_DESC @8

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0atrap1.PRO~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0atrap2.PRO~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0atrap3.PRO~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0atrap4.PRO~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0atrap5.PRO~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0atrap6.PRO~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0atrap7.PRO~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0atrap8.PRO~

COPY_EXISTING ~c0atrap1.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0atrap1%~
END
COPY_EXISTING ~c0atrap5.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0atrap5%~
END
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = FIRE
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 142
	  parameter2 = c0aicon3
END
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139
        parameter1 		  = RESOLVE_STR_REF (@9)
      END
COPY_EXISTING ~c0auin1a.spl~ ~override~
SAY NAME1 @10
SAY NAME2 @10

COPY_EXISTING ~c0atrap2.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0atrap2%~
END
COPY_EXISTING ~c0atrap6.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0atrap6%~
END
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = COLD
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139
        parameter1 		  = RESOLVE_STR_REF (@11)
      END
COPY_EXISTING ~c0auin1b.spl~ ~override~
SAY NAME1 @12
SAY NAME2 @12

COPY_EXISTING ~c0atrap3.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0atrap3%~
END
COPY_EXISTING ~c0atrap7.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0atrap7%~
END
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ACID
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139
        parameter1 		  = RESOLVE_STR_REF (@13)
      END
COPY_EXISTING ~c0auin1c.spl~ ~override~
SAY NAME1 @14
SAY NAME2 @14

COPY_EXISTING ~c0atrap4.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0atrap4%~
END
COPY_EXISTING ~c0atrap8.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0atrap8%~
END
		LPF	ADD_SPELL_EFFECT
			INT_VAR
				insert_point = 0
				opcode = 324
				target = 2
				parameter2 = ELEC
				duration = 1
			STR_VAR
				resource = EVAL ~%SOURCE_RES%~
		END
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 142   // Display portrait icon
        parameter2        = c0aicon6
      END
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139
        parameter1 		  = RESOLVE_STR_REF (@15)
      END
COPY_EXISTING ~c0aparal.spl~ ~override~
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139
        parameter1 		  = RESOLVE_STR_REF (@16)
      END
COPY_EXISTING ~c0auin1d.spl~ ~override~
SAY NAME1 @17
SAY NAME2 @17

COPY_EXISTING ~c0aualc.spl~ ~override~
SAY NAME1 @18
SAY NAME2 @18
SAY UNIDENTIFIED_DESC @19

COPY_EXISTING ~c0aualch.cre~ ~override~
SAY NAME1 @20
SAY NAME2 @20
  WRITE_ASCII 0x248 ~c0aualch~ #8  //override script
  WRITE_ASCII 0x280 ~c0aualch~ #32  //DV
  WRITE_ASCII 0x2cc ~c0aualch~ #8   //pre-joining dialogue file
  WRITE_ASCII 0x268 ~c0aualch~ #8   //default
   WRITE_ASCII 0X34 ~c0aualch~ #8   //small portrait
  COMPILE ~%MOD_FOLDER%/dialogue/c0aualch.d~
  COMPILE ~%MOD_FOLDER%/scripts/c0aualch.baf~
  
COPY_EXISTING ~c0aualc1.spl~ ~override~
COPY_EXISTING ~c0aualc2.spl~ ~override~
COPY_EXISTING ~c0aualc3.spl~ ~override~
  
COPY_EXISTING ~c0autinv.sto~ ~override~
SAY 0xc @21

COPY_EXISTING ~c0aupot1.sto~ ~override/c0aupot1.sto~
SAY 0xc @22
  
COPY_EXISTING ~c0aupot1.sto~ ~override/c0aubom1.sto~
SAY 0xc @23

COPY_EXISTING ~c0aupot1.sto~ ~override/c0aupoth.sto~
SAY 0xc @24

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/scripts/baldur.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/scripts/baldur.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/scripts/baldur.baf~
END

COPY_EXISTING ~c0ausumm.cre~ ~override~
  WRITE_ASCII 0x248 ~C0MSumm~ #8  //override script
COPY_EXISTING ~c0auin3.spl~ ~override~
SAY NAME1 @25
SAY NAME2 @25
SAY UNIDENTIFIED_DESC @26

COPY_EXISTING ~c0auin4.spl~ ~override~
SAY NAME1 @27
SAY NAME2 @27
SAY UNIDENTIFIED_DESC @28
COPY_EXISTING ~c0aualch.cre~ ~override/c0auin4.cre~
SAY NAME1 @29
SAY NAME2 @29
  WRITE_ASCII 0x248 ~c0auin4~ #8  //override script
  WRITE_ASCII 0x280 ~c0auin4~ #32  //DV
  WRITE_ASCII 0x2cc ~c0auin4~ #8   //pre-joining dialogue file
  WRITE_ASCII 0x268 ~c0auin4~ #8   //default
COPY_EXISTING ~c0auin5.spl~ ~override~
SAY NAME1 @30
SAY NAME2 @30
SAY UNIDENTIFIED_DESC @31

COPY_EXISTING ~c0auin6.spl~ ~override~
      LPF ALTER_EFFECT
      INT_VAR
        check_globals     = 0
        check_headers     = 1
        match_opcode      = 142   // Display portrait icon
        match_parameter2  = 82    // Called Shot icon
        parameter2        = c0aicon5
      END
SAY NAME1 @32
SAY NAME2 @32
SAY UNIDENTIFIED_DESC @33

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////// POTIONS /////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

COPY_EXISTING ~c0apot01.spl~ ~override~
SAY NAME1 @34
SAY NAME2 @34
COPY_EXISTING ~c0apot01.itm~ ~override~
SAY NAME1 @35
SAY NAME2 @35
SAY DESC @36
WRITE_LONG 0x34 200
 
COPY_EXISTING ~c0apot02.spl~ ~override~
SAY NAME1 @37
SAY NAME2 @37
COPY_EXISTING ~c0apot02.itm~ ~override~
SAY NAME1 @38
SAY NAME2 @38
SAY DESC @39
WRITE_LONG 0x34 250

COPY_EXISTING ~c0apot03.spl~ ~override~
SAY NAME1 @40
SAY NAME2 @40
COPY_EXISTING ~c0apot03.itm~ ~override~
SAY NAME1 @41
SAY NAME2 @41
SAY DESC @42
WRITE_LONG 0x34 250

COPY_EXISTING ~c0apot04.spl~ ~override~
SAY NAME1 @43
SAY NAME2 @43
COPY_EXISTING ~c0apot04.itm~ ~override~
SAY NAME1 @44
SAY NAME2 @44
SAY DESC @45
WRITE_LONG 0x34 160

COPY_EXISTING ~c0apot05.spl~ ~override~
SAY NAME1 @46
SAY NAME2 @46
COPY_EXISTING ~c0apot05.itm~ ~override~
SAY NAME1 @47
SAY NAME2 @47
SAY DESC @48
WRITE_LONG 0x34 180

COPY_EXISTING ~c0apot06.spl~ ~override~
SAY NAME1 @49
SAY NAME2 @49
COPY_EXISTING ~c0apot06.itm~ ~override~
SAY NAME1 @50
SAY NAME2 @50
SAY DESC @51
WRITE_LONG 0x34 500

COPY_EXISTING ~c0apot07.spl~ ~override~
SAY NAME1 @52
SAY NAME2 @52
COPY_EXISTING ~c0apot07.itm~ ~override~
SAY NAME1 @53
SAY NAME2 @53
SAY DESC @54
WRITE_LONG 0x34 500

COPY_EXISTING ~c0apot08.spl~ ~override~
SAY NAME1 @55
SAY NAME2 @55
COPY_EXISTING ~c0apot08.itm~ ~override~
SAY NAME1 @56
SAY NAME2 @56
SAY DESC @57
WRITE_LONG 0x34 600

COPY_EXISTING ~c0apot09.spl~ ~override~
SAY NAME1 @58
SAY NAME2 @58
COPY_EXISTING ~c0apot09.itm~ ~override~
SAY NAME1 @59
SAY NAME2 @59
SAY DESC @60
WRITE_LONG 0x34 1000

COPY_EXISTING ~c0apot10.spl~ ~override~
SAY NAME1 @61
SAY NAME2 @61
COPY_EXISTING ~c0apot10.itm~ ~override~
SAY NAME1 @62
SAY NAME2 @62
SAY DESC @63
WRITE_LONG 0x34 900

COPY_EXISTING ~c0apot11.spl~ ~override~
SAY NAME1 @64
SAY NAME2 @64
COPY_EXISTING ~c0apot11.itm~ ~override~
SAY NAME1 @65
SAY NAME2 @65
SAY DESC @66
WRITE_LONG 0x34 300

COPY_EXISTING ~c0apot12.spl~ ~override~
SAY NAME1 @67
SAY NAME2 @67
COPY_EXISTING ~c0apot12.itm~ ~override~
SAY NAME1 @68
SAY NAME2 @68
SAY DESC @69
WRITE_LONG 0x34 700

COPY_EXISTING ~c0apot13.spl~ ~override~
SAY NAME1 @70
SAY NAME2 @70
COPY_EXISTING ~c0apot13.itm~ ~override~
SAY NAME1 @71
SAY NAME2 @71
SAY DESC @72
WRITE_LONG 0x34 1000

COPY_EXISTING ~c0apot14.spl~ ~override~
SAY NAME1 @73
SAY NAME2 @73
COPY_EXISTING ~c0apot14.itm~ ~override~
SAY NAME1 @74
SAY NAME2 @74
SAY DESC @75
WRITE_LONG 0x34 150

COPY_EXISTING ~c0apot15.spl~ ~override~
SAY NAME1 @76
SAY NAME2 @76
COPY_EXISTING ~c0apot15.itm~ ~override~
SAY NAME1 @77
SAY NAME2 @77
SAY DESC @78
WRITE_LONG 0x34 450

COPY_EXISTING ~c0apot16.spl~ ~override~
SAY NAME1 @79
SAY NAME2 @79
COPY_EXISTING ~c0apot16.itm~ ~override~
SAY NAME1 @80
SAY NAME2 @80
SAY DESC @81
WRITE_LONG 0x34 500

COPY_EXISTING ~c0apot17.spl~ ~override~
SAY NAME1 @82
SAY NAME2 @82
COPY_EXISTING ~c0apot17.itm~ ~override~
SAY NAME1 @83
SAY NAME2 @83
SAY DESC @84
WRITE_LONG 0x34 500

COPY_EXISTING ~c0apot18.spl~ ~override~
SAY NAME1 @85
SAY NAME2 @85
COPY_EXISTING ~c0apot18.itm~ ~override~
SAY NAME1 @86
SAY NAME2 @86
SAY DESC @87
WRITE_LONG 0x34 600

COPY_EXISTING ~c0apot19.spl~ ~override~
SAY NAME1 @88
SAY NAME2 @88
COPY_EXISTING ~c0apot19.itm~ ~override~
SAY NAME1 @89
SAY NAME2 @89
SAY DESC @90
WRITE_LONG 0x34 700

COPY_EXISTING ~c0apot20.spl~ ~override~
SAY NAME1 @91
SAY NAME2 @91
COPY_EXISTING ~c0apot20.itm~ ~override~
SAY NAME1 @92
SAY NAME2 @92
SAY DESC @93
WRITE_LONG 0x34 700

COPY_EXISTING ~c0apot21.spl~ ~override~
SAY NAME1 @94
SAY NAME2 @94
COPY_EXISTING ~c0apot21.itm~ ~override~
SAY NAME1 @95
SAY NAME2 @95
SAY DESC @96
WRITE_LONG 0x34 1200

COPY_EXISTING ~c0apot22.spl~ ~override~
SAY NAME1 @97
SAY NAME2 @97
COPY_EXISTING ~c0apot22.itm~ ~override~
SAY NAME1 @98
SAY NAME2 @98
SAY DESC @99
WRITE_LONG 0x34 1500

COPY_EXISTING ~c0apoth1.itm~ ~override~
SAY NAME1 @100
SAY NAME2 @100
SAY DESC @101
WRITE_LONG 0x34 2000

COPY_EXISTING ~c0apoth2.itm~ ~override~
SAY NAME1 @102
SAY NAME2 @102
SAY DESC @103
WRITE_LONG 0x34 2000

COPY_EXISTING ~c0apoth3.itm~ ~override~
SAY NAME1 @104
SAY NAME2 @104
SAY DESC @105
WRITE_LONG 0x34 2000

COPY_EXISTING ~c0apoth4.itm~ ~override~
SAY NAME1 @106
SAY NAME2 @106
SAY DESC @107
WRITE_LONG 0x34 2000

COPY_EXISTING ~c0apoth5.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (@108)
  END
SAY NAME1 @109
COPY_EXISTING ~c0apoth5.itm~ ~override~
SAY NAME1 @110
SAY NAME2 @110
SAY DESC @111
WRITE_LONG 0x34 15000

  COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/scripts/c0au#at1.baf~
COPY ~%MOD_FOLDER%/creatures/c0au#at1.cre~ ~override~
WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~C0_AUTOCANNON~))
WRITE_ASCII SCRIPT_DEFAULT ~c0au#at1~  // override
WRITE_ASCII DEATHVAR ~c0au#at1~ // death variable
SAY NAME1 @112
SAY NAME2 @112

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0au#sp2.PRO~
COPY_EXISTING ~c0au#s1.spl~ ~override~
SAY NAME1 @113
SAY UNIDENTIFIED_DESC @114
COPY_EXISTING ~c0au#s2.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0au#sp2%~
END
