//AUDIO

LAF HANDLE_AUDIO END

DEFINE_PATCH_FUNCTION ~GET_2DA_ROW~
	INT_VAR
		starting_row=0
		numcolumns=0
		match_column=0
		found_it=0
	STR_VAR
		match=~DEFA~
	RET
		numcols
		matched
BEGIN
		COUNT_2DA_ROWS numcolumns numrows
		FOR (i = starting_row; i < numrows; ++i) BEGIN
			READ_2DA_ENTRY i match_column numcolumns string_to_match
			PATCH_IF (~%string_to_match%~ STRING_EQUAL_CASE ~%match%~) BEGIN
				matched = i
				found_it = 1
				i = numrows

			END
		END
		numcols = numcolumns
		PATCH_IF (found_it = 0) BEGIN
			PATCH_FAIL @115
		END
END
	
ADD_MUSIC ~C0MMMUS~ ~%MOD_FOLDER%/music/C0MMMUS.mus~
COPY ~%MOD_FOLDER%/music/c0mmmusa.acm~ ~MUSIC/C0MMMUS/c0mmmusa.acm~

COPY_EXISTING ~SONGLIST.2da~ ~override~
	LPF GET_2DA_ROW INT_VAR numcolumns=3 match_column=2 STR_VAR match=~C0MMMUS.mus~ RET therow=matched END
	READ_2DA_ENTRY therow 0 3 ~song~

	OUTER_SET C0MMMUS = song

///////////////
// CREATURES //
///////////////

// SINGLE-CLASS ARTIFICER
COPY ~%MOD_FOLDER%/creatures/C0MMin.cre~ ~override~
  SAY NAME1 @116
  SAY NAME2 @116
  WRITE_ASCII SCRIPT_OVERRIDE ~C0MMINS~ // override
  WRITE_ASCII DEATHVAR ~C0MMIN~ // death variable
  WRITE_ASCII DIALOG ~C0MMIN~ // dialogue
  WRITE_ASCII 0X34 ~C0MMINM~ #8   //small portrait
  WRITE_ASCII 0x3c ~C0MMINL~ #8   //medium portrait
  SAY BIO @117
  SAY MORALE ~~
  SAY LEADER @119
  SAY TIRED @120
  SAY BORED @121
  SAY BATTLE_CRY1 @122
  SAY BATTLE_CRY2 @123
  SAY BATTLE_CRY3 @124
  SAY BATTLE_CRY4 @125
  SAY BATTLE_CRY5 @126
  SAY DAMAGE @127
  SAY DYING @128
  SAY HURT @129
  SAY AREA_FOREST @130
  SAY AREA_CITY @131
  SAY AREA_DUNGEON @132
  SAY AREA_DAY @133
  SAY AREA_NIGHT @134
  SAY SELECT_COMMON1 @135
  SAY SELECT_COMMON2 @136
  SAY SELECT_COMMON3 @137
  SAY SELECT_COMMON4 @138
  SAY SELECT_COMMON5 @139
  SAY SELECT_ACTION1 @140
  SAY SELECT_ACTION2 @141
  SAY SELECT_ACTION3 @142
  SAY SELECT_ACTION4 @143
  SAY SELECT_ACTION5 @144
  SAY SELECT_ACTION6 @145
  SAY SELECT_ACTION7 @146
  SAY CRITICAL_HIT @147
  SAY CRITICAL_MISS @148
  SAY TARGET_IMMUNE @149
  SAY INVENTORY_FULL @150
  SAY SPELL_DISRUPTED @151
  SAY SET_A_TRAP @152
  SAY HIDDEN_IN_SHADOWS @153
  SAY PICKED_POCKET @154
  WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0ARFT~))

APPEND ~pdialog.2da~ ~C0MMIN     C0MMINP           C0MMINJ          C0MMIND       C0MMINP           C0MMINJ              C0MMIND              C0MMIN~
UNLESS ~C0MMIN~

APPEND ~interdia.2da~ ~C0MMIN BC0MMIN BC0MMIN~
  UNLESS ~C0MMIN~

APPEND ~STATE.IDS~ // adds custom IsValidForPartyDialogue state
  ~0x80101FEF CD_STATE_NOTVALID~
  UNLESS ~CD_STATE_NOTVALID~
  
EXTEND_TOP ~AR1000.bcs~ ~%MOD_FOLDER%/Scripts/AR1000.baf~

LAF ALTER_SCRIPT_BLOCK
      STR_VAR script=kuarundd
			  swap_out=~!Allegiance(Myself,ENEMY)~
			  swap_in=~!InMyArea("C0MMin")InParty("C0MMin")!Allegiance(Myself,ENEMY)~
END

COMPILE EVAL ~%MOD_FOLDER%/Scripts/C0MMinS.baf~
		~%MOD_FOLDER%/Scripts/C0MMinD.baf~
		~%MOD_FOLDER%/Scripts/C0MMinR.baf~
		~%MOD_FOLDER%/Scripts/C0MODR.baf~
		~%MOD_FOLDER%/Scripts/C0MSumm.baf~

COMPILE EVAL ~%MOD_FOLDER%/Dialogue/C0MMin.d~
		~%MOD_FOLDER%/Dialogue/C0MMinJ.d~
		~%MOD_FOLDER%/Dialogue/C0MODR.d~
		~%MOD_FOLDER%/Dialogue/BC0MMin.d~
  
COPY_EXISTING ~DAGG11.itm~ ~override~
SAY NAME1 #6343
SAY NAME2 @155
SAY UNIDENTIFIED_DESC #6720
SAY DESC @156

OUTER_SET DAGG11A = RESOLVE_STR_REF (@157)
OUTER_SET DAGG11B = RESOLVE_STR_REF (@158)
APPEND TOOLTIP.2DA ~DAGG11 %DAGG11B% %DAGG11A% -1~ UNLESS ~DAGG11~
  
COPY_EXISTING ~DAGG12.itm~ ~override~
SAY NAME1 #6343
SAY NAME2 @159
SAY UNIDENTIFIED_DESC #6720
SAY DESC @160

OUTER_SET DAGG12A = RESOLVE_STR_REF (@157)
OUTER_SET DAGG12B = RESOLVE_STR_REF (@158)
APPEND TOOLTIP.2DA ~DAGG12 %DAGG12B% %DAGG12A% -1~ UNLESS ~DAGG12~

ACTION_IF FILE_EXISTS_IN_GAME ~KUSMITH.sto~ THEN BEGIN
COPY_EXISTING ~KUSMITH.sto~ ~override~
ADD_STORE_ITEM ~DAGG11~ BEFORE ~RELIAN~ #0 #0 #0 ~IDENTIFIED~ #1
END
  
ACTION_IF FILE_EXISTS_IN_GAME ~LDD_NYM.sto~ THEN BEGIN
COPY_EXISTING ~LDD_NYM.sto~ ~override~
ADD_STORE_ITEM ~DAGG12~ AFTER ~MYSTERY~ #0 #0 #0 ~IDENTIFIED~ #1
END
  
COPY_EXISTING ~C0MBrac1.itm~ ~override~
SAY NAME1 @161
SAY NAME2 @162
SAY DESC @163
OUTER_SET strref = RESOLVE_STR_REF (@164)
APPEND item_use.2da ~C0MBrac1 Minerva %strref% 3~

COPY_EXISTING ~C0MBrac1.sto~ ~override~
SAY 0xc @165

COPY_EXISTING ~C0MDaggS.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0mboom%~
END
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139   // Display portrait icon
        parameter1 = RESOLVE_STR_REF (@166)
      END
COPY_EXISTING ~C0MDagg1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0ARFT~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (@6)
END
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139   // Display portrait icon
        parameter1 = RESOLVE_STR_REF (@166)
      END
SAY NAME1 @167
SAY NAME2 @168
SAY DESC @169

COPY_EXISTING ~C0MDagg2.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0ARFT~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (@6)
END
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139   // Display portrait icon
        parameter1 = RESOLVE_STR_REF (@166)
      END
SAY NAME1 @167
SAY NAME2 @170
SAY DESC @171

COPY_EXISTING ~C0MDagg3.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0ARFT~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (@6)
END
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139   // Display portrait icon
        parameter1 = RESOLVE_STR_REF (@166)
      END
SAY NAME1 @167
SAY NAME2 @172
SAY DESC @173

COPY_EXISTING ~BELTGON.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 177
	  target = 1
	  timing = 2
	  parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0ARFT~)
	  parameter2 = 9
	STR_VAR
	  resource = C0MBELT1
END
SAY DESC @174

COPY_EXISTING ~C0MFISH.itm~ ~override~
SAY NAME1 @175
SAY NAME2 @175
SAY DESC @176

COPY_EXISTING ~CDGOND.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 177
	  target = 1
	  timing = 2
	  parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0ARFT~)
	  parameter2 = 9
	STR_VAR
	  resource = C0MBELT2
END
SAY DESC @177

COPY_EXISTING ~C0MSICK1.SPL~ ~override~
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139   // Display portrait icon
        parameter1 = RESOLVE_STR_REF (@178)
      END

COPY_EXISTING ~C0MSICK2.SPL~ ~override~
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139   // Display portrait icon
        parameter1 = RESOLVE_STR_REF (@179)
      END

COPY_EXISTING ~C0MSP01.SPL~ ~override~
      LPF ALTER_EFFECT
      INT_VAR
        match_opcode      = 139   // Display portrait icon
        parameter1 = RESOLVE_STR_REF (@166)
      END
	  
SAY NAME1 @180
SAY UNIDENTIFIED_DESC @181

COPY_EXISTING ~C0MMOD1.cre~ ~override~
  WRITE_ASCII 0X34 ~C0MODR~ #8   //small portrait
SAY NAME1 @182
SAY NAME2 @182
WRITE_ASCII 0x2cc ~C0MODR~  #8  // dialogue
  WRITE_ASCII 0x280 ~C0MODR~ #32  //DV
    WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~C0_MODRON~))

COPY_EXISTING ~C0MMOD2.cre~ ~override~
  WRITE_ASCII 0X34 ~C0MODR~ #8   //small portrait
SAY NAME1 @183
SAY NAME2 @183
WRITE_ASCII 0x2cc ~C0MODR~  #8  // dialogue
  WRITE_ASCII 0x280 ~C0MODR~ #32  //DV
    WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~C0_MODRON~))

COPY_EXISTING ~C0MMOD3.cre~ ~override~
  WRITE_ASCII 0X34 ~C0MODR~ #8   //small portrait
SAY NAME1 @184
SAY NAME2 @184
WRITE_ASCII 0x2cc ~C0MODR~  #8  // dialogue
  WRITE_ASCII 0x280 ~C0MODR~ #32  //DV
    WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~C0_MODRON~))
	
COPY_EXISTING ~c0mnktn.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 290 parameter1 = RESOLVE_STR_REF (@6) END